### ISSUE TITLE
Enable codecov

### ISSUE THREAD

**Issue by andrewhabib** [IBM/jsonsubschema#3]
Hi @stevemar 

Can you please enable codecov for this repository?

Thakn you,

**Comment by stevemar** [comment]
@andrewhabib codecov is enabled by default for all repos. 

I'm not sure if you can log into the codecov console, but check out https://codecov.io/gh/IBM/jsonsubschema/ for how to enable it for this repo

Failing that, check out the sample python repo: https://github.com/codecov/example-python

and their docs: https://docs.codecov.io/docs

**Comment by andrewhabib** [comment]
Yes, you are right. It is enabled. 
Thank you,
