### ISSUE TITLE
Infinite Loop in test_boolean.py::TestNotBoolean::test_not_allOf1 with not and allOf Connectors

### ISSUE THREAD

**Issue by hizoben** [IBM/jsonsubschema#33]
I found a bug in the library where certain tests, such as `test_boolean.py::TestNotBoolean::test_not_allOf1`, enter an infinite loop. The issue occurs when both `not` and `allOf` connectors are used together. The problematic code is here:

```python
elif c == "allOf":
    # anyofs = []
    # for i in negated_schema["allOf"]:
    #     anyofs.append(canonicalize_not({"not": i}))
    # return {"anyOf": anyofs}
    return canonicalize_not({'not': canonicalize_connectors(negated_schema)})
```

This causes an infinite loop.

**Proposed Fix:**

I suggest the following changes to fix the issue:

1. Replace the problematic code with:

```python
elif c == "allOf":
    return {'not': canonicalize_connectors(negated_schema)}
```

2. Update the `simplify_schema_and_embed_checkers` method as follows:

```python
if "not" in s:
    negate_schema = simplify_schema_and_embed_checkers(s["not"])
    return typeToConstructor.get(negate_schema["type"]).neg(negate_schema)
```

3. Add a `neg` method to the `JsnoBot` object to return a `jsonTop`.

**Steps to Reproduce:**

1. Run the test `test_boolean.py::TestNotBoolean::test_not_allOf1`.
2. Observe that the test enters an infinite loop.

**Expected Behavior:**

The test should complete and pass without entering an infinite loop.

**Additional Context:**

The bug arises when handling schemas with nested `not` and `allOf` connectors. My proposed changes should address the issue while preserving the library's expected functionality.

**Comment by shinnar** [comment]
I am unable to reproduce the described issue.  CI runs the indicated test successfully.  If you have more information on reproducing this issue, please re-open the issue with more details.
